### PR TITLE
Woodpecker

### PR DESCRIPTION
**Pull request by JoelBradley**
Alternative to github actions. Gives us more control and more unlimited use.
Can also use this server to deploy to.

### CODE REVIEW

**Review by dannyb648 — COMMENTED** [review]
do we need seperate access for woodpecker? Can you add a readme with the links in?

**Comment by JoelBradley** [comment]
> do we need seperate access for woodpecker? Can you add a readme with the links in?

You should be able to see Woodpecker building on this pull request. If you click on details I think it'll make you sign in with GitHub. I'm not really sure what the process looks like for you because I had to do it differently to get it set up in the first place.

It's running on a server in my house.

**Comment by JoelBradley** [comment]
@dannyb648 I think I need to add you actually. So I'll work out doing that

**Comment by JoelBradley** [comment]
@dannyb648 Everyone in this organisation should be able to access it now if I've done it right.
http://86.10.52.251:8000/

**Comment by JoelBradley** [comment]
Woodpecker now, lints, runs tests, compiles the code for pull requests and deploys to http://86.10.52.251/ when a change is pushed to `main`

**Review by dannyb648 — APPROVED** [review]

**Pull request merged**
